package com.example.soundrecorder.utils

const val SIGN_UP = "register"
const val GET_ALL_USER = "getAllUser"
const val UPLOAD_RESULT = "uploadResult"
const val GET_DATA_ANALYSIS = "getDataAnalysis"
const val GET_DATA_ANALYSIS_ONE = "getDataAnalysisOne"
const val VIEW_LISTING = "viewLisitng"
const val GET_ALL_STATE = "getAllState"
const val GET_BULLETS = "getBullets"
const val GET_ALL_COUNTRIES = "getAllCountries"
const val LOGIN = "login"
const val GET_CALCULATION = "getCalculation"
const val GEL_ALL_OPTIONS = "getAllOptions"
const val FORGOT_PASSWORD = "forgotPassword"
const val VIEW_LISTING_ONE = "viewLisitngOne"
const val VIEW_LISTING_THREE = "viewLisitngThree"
const val UPDATE_PROFILE = "updateProfile"
const val SEND_PAYMENT = "sendPayment"
